"""
Pydantic schemas for RapRank NLP Service v2.
"""
from __future__ import annotations

from typing import List, Optional
from pydantic import BaseModel, Field


# ── Request ───────────────────────────────────────────────────────────────────

class WordTimestamp(BaseModel):
    """Word-level timing entry from faster-whisper."""
    word: str
    start: float
    end: float


class AnalyzeRequest(BaseModel):
    lyrics: str = Field(..., description="Full lyric text to analyse.")
    language: str = Field(
        default="auto",
        description="ISO language hint: 'en', 'hi', or 'auto' for auto-detect.",
    )
    words: Optional[List[WordTimestamp]] = Field(
        default=None,
        description=(
            "Word-level timestamps from faster-whisper. "
            "When provided, enables flow/beat-sync scoring without audio."
        ),
    )
    audio_url: Optional[str] = Field(
        default=None,
        description="Absolute URL to download the audio track for flow scoring.",
    )
    track_id: Optional[int] = Field(
        default=None,
        description="Optional core registry database track ID for real-time status updates.",
    )


# ── Sub-models ────────────────────────────────────────────────────────────────

class RhymeMatch(BaseModel):
    """A detected rhyme pair between two lyric lines."""
    line_a: int = Field(..., description="0-based index of the first line.")
    line_b: int = Field(..., description="0-based index of the second line.")
    word_a: str
    word_b: str
    is_multisyllabic: bool = Field(
        ..., description="True when ≥2 syllable groups match (richer rhyme)."
    )


class FlowMetadata(BaseModel):
    """Diagnostic data from beat-sync analysis."""
    tempo_bpm: float
    on_beat_ratio: float = Field(..., description="Fraction of word onsets landing on a beat.")
    avg_deviation_ms: float = Field(..., description="Mean ms distance from nearest beat.")
    words_analyzed: int
    syllable_rate: Optional[float] = Field(default=None, description="Syllables per second.")
    complexity_bonus: Optional[float] = Field(default=None, description="Flow complexity bonus.")
    cadence_variance: Optional[float] = Field(default=None, description="Standard deviation of syllable rate across intervals.")
    flow_switch_bonus: Optional[float] = Field(default=None, description="Flow switch / cadence versatility bonus.")


# ── Response ──────────────────────────────────────────────────────────────────

class ScoreBreakdown(BaseModel):
    # ── Core scores ──────────────────────────────────────────
    syllable_score: float = Field(..., ge=0, le=100)
    rhyme_score: float = Field(..., ge=0, le=100)
    alliteration_score: float = Field(..., ge=0, le=100)
    vocabulary_score: float = Field(..., ge=0, le=100)
    flow_score: Optional[float] = Field(
        default=None,
        description="Beat-sync score (0-100). null when audio not provided.",
    )
    total_score: float = Field(..., ge=0, le=100)

    # ── New scores ───────────────────────────────────────────
    wordplay_score: float = Field(..., ge=0, le=100)
    syllable_weight: float = Field(..., ge=0, le=100)

    # ── Stats ─────────────────────────────────────────────────
    word_count: int
    line_count: int
    avg_syllables_per_word: float
    vocabulary_uniqueness: float = Field(..., description="Type-token ratio (0-1).")
    detected_language: str = Field(..., description="'en', 'hi', or 'mixed'.")

    # ── Wordplay stats ───────────────────────────────────────
    double_entendres_count: int
    puns_count: int
    similes_count: int
    metaphors_count: int

    # ── Detail lists ─────────────────────────────────────────
    alliteration_pairs: List[str]
    rhyme_pairs: List[RhymeMatch]
    multisyllabic_rhyme_count: int
    flow_metadata: Optional[FlowMetadata] = None
    generated_lyrics: Optional[str] = Field(default=None, description="Mistral formatted lyrics.")
    wordplay_explanation: Optional[str] = Field(default=None, description="Detailed explanation of metaphors, puns, and double meanings generated by Mistral.")
    nlp_explanations: Optional[dict] = Field(default=None, description="Detailed explanations of rhyme, syllable, alliteration, and vocabulary scoring generated by Mistral.")

