-- ─────────────────────────────────────────────────────────────────────────────
-- RapRank Database Setup (Safe for Docker and Local installs)
-- ─────────────────────────────────────────────────────────────────────────────
-- NOTE: In docker-compose, the database 'raprank_db' and user 'raprank_user'
-- are created automatically via environment variables. Executing raw CREATE DB
-- or CREATE USER statements during startup will cause the container to crash.
--
-- This file is left empty/safe. For manual bare-metal setups, refer to the
-- README.md or run these commands manually in your psql client.
-- ─────────────────────────────────────────────────────────────────────────────
