"""Auto-generated by derive_english_tiers.py -- KAGGLE_ARTIST_TIERS is the
critical-consensus tier (same sourcing convention as real_artists.py's
REAL_ARTIST_TIERS), not the measured density composite -- see that script's
module docstring for why the measured-density approach was rejected.
Regenerate by re-running that script; do not hand-edit.
"""

KAGGLE_ARTIST_TIERS: dict[str, str] = {
    "2Pac": "elite",
    "Dave": "mid",
    "Drake": "commercial",
    "Eminem": "elite",
    "Future": "commercial",
    "J. Cole": "elite",
    "Kendrick Lamar": "elite",
    "Nas": "elite",
    "Nicki Minaj": "commercial",
    "Rapsody": "elite",
    "Skepta": "mid"
}
